### ISSUE TITLE
Error when running parse.py

### ISSUE THREAD

**Issue by fullofcaffeine** [foursquare/twofishes#62]
Trying to get the app up and running in order to play with the data from quattroshapes. I have a vagrant VBOX VM with 4GB of RAM. I start mongo and then:

$ ./parse.py -c MX

After a while, it fails with:

```
[info] 00:00:41,282 |-INFO in ch.qos.logback.classic.joran.JoranConfigurator@132424db - Registering current configuration as safe fallback point
[error] SLF4J: Actual binding is of type [ch.qos.logback.classic.util.ContextSelectorStaticBinder]
[info] 234   INFO  c.f.twofishes.util.Helpers$ - readSlugs took 0 seconds
[error] java.nio.charset.MalformedInputException: Input length = 1
[error]         at java.nio.charset.CoderResult.throwException(CoderResult.java:277)
[error]         at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:338)
[error]         at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:177)
[error]         at java.io.InputStreamReader.read(InputStreamReader.java:184)
[error]         at java.io.BufferedReader.fill(BufferedReader.java:154)
[error]         at java.io.BufferedReader.readLine(BufferedReader.java:317)
[error]         at java.io.BufferedReader.readLine(BufferedReader.java:382)
[error]         at scala.io.BufferedSource$BufferedLineIterator.hasNext(BufferedSource.scala:67)
[error]         at scala.collection.Iterator$class.foreach(Iterator.scala:727)
[error]         at scala.collection.AbstractIterator.foreach(Iterator.scala:1157)
[error]         at scala.collection.generic.Growable$class.$plus$plus$eq(Growable.scala:48)
[error]         at scala.collection.mutable.ListBuffer.$plus$plus$eq(ListBuffer.scala:176)
[error]         at scala.collection.mutable.ListBuffer.$plus$plus$eq(ListBuffer.scala:45)
[error]         at scala.collection.TraversableOnce$class.to(TraversableOnce.scala:273)
[error]         at scala.collection.AbstractIterator.to(Iterator.scala:1157)
[error]         at scala.collection.TraversableOnce$class.toList(TraversableOnce.scala:257)
[error]         at scala.collection.AbstractIterator.toList(Iterator.scala:1157)
[error]         at com.foursquare.twofishes.importers.geonames.GeonamesParser.deletesList$lzycompute(GeonamesParser.scala:188)
[error]         at com.foursquare.twofishes.importers.geonames.GeonamesParser.deletesList(GeonamesParser.scala:187)
[error]         at com.foursquare.twofishes.importers.geonames.GeonamesParser.<init>(GeonamesParser.scala:324)
[error]         at com.foursquare.twofishes.importers.geonames.GeonamesParser$.main(GeonamesParser.scala:86)
[error]         at com.foursquare.twofishes.importers.geonames.GeonamesParser.main(GeonamesParser.scala)
[error]         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[error]         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
[error]         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[error]         at java.lang.reflect.Method.invoke(Method.java:606)
[error]         at scala.tools.nsc.util.ScalaClassLoader$$anonfun$run$1.apply(ScalaClassLoader.scala:71)
[error]         at scala.tools.nsc.util.ScalaClassLoader$class.asContext(ScalaClassLoader.scala:31)
[error]         at scala.tools.nsc.util.ScalaClassLoader$URLClassLoader.asContext(ScalaClassLoader.scala:139)
[error]         at scala.tools.nsc.util.ScalaClassLoader$class.run(ScalaClassLoader.scala:71)
[error]         at scala.tools.nsc.util.ScalaClassLoader$URLClassLoader.run(ScalaClassLoader.scala:139)
[error]         at scala.tools.nsc.CommonRunner$class.run(ObjectRunner.scala:28)
[error]         at scala.tools.nsc.ObjectRunner$.run(ObjectRunner.scala:45)
[error]         at scala.tools.nsc.CommonRunner$class.runAndCatch(ObjectRunner.scala:35)
[error]         at scala.tools.nsc.ObjectRunner$.runAndCatch(ObjectRunner.scala:45)
[error]         at scala.tools.nsc.MainGenericRunner.runTarget$1(MainGenericRunner.scala:74)
[error]         at scala.tools.nsc.MainGenericRunner.process(MainGenericRunner.scala:96)
[error]         at scala.tools.nsc.MainGenericRunner$.main(MainGenericRunner.scala:105)
[error]         at scala.tools.nsc.MainGenericRunner.main(MainGenericRunner.scala)
java.lang.RuntimeException: Nonzero exit code returned from runner: 1
        at scala.sys.package$.error(package.scala:27)
[trace] Stack trace suppressed: run last indexer/compile:run-main for the full output.
[error] (indexer/compile:run-main) Nonzero exit code returned from runner: 1
[error] Total time: 5 s, completed Apr 26, 2015 12:00:42 AM
```

What could be wrong?

**Comment by rahulpratapm** [comment]
Is your default locale not using UTF-8?

You could run "locale" at the terminal or, in python:

import locale
locale.getdefaultlocale()[1]

If it isn't, you should be able to do export LANG=en_US.UTF-8.

Rahul.

**Comment by fullofcaffeine** [comment]
@rahulpratapm Thanks, that was the problem.
