### ISSUE TITLE
Unable to resolve dependencies

### ISSUE THREAD

**Issue by gustavo-momente** [foursquare/twofishes#73]
Wen trying to build the server using `./sbt server/assembly` two dependencies aren't found:

    [warn]  ::::::::::::::::::::::::::::::::::::::::::::::
    [warn]  ::          UNRESOLVED DEPENDENCIES         ::
    [warn]  ::::::::::::::::::::::::::::::::::::::::::::::
    [warn]  :: com.eed3si9n#sbt-assembly;0.9.2: not found
    [warn]  :: com.typesafe.sbt#sbt-pgp;0.8.3: not found
    [warn]  ::::::::::::::::::::::::::::::::::::::::::::::
    [warn]
    [warn]  Note: Some unresolved dependencies have extra attributes.  Check that these dependencies exist with the requested attributes.
    [warn]          com.eed3si9n:sbt-assembly:0.9.2 (sbtVersion=0.12, scalaVersion=2.9.2)
    [warn]          com.typesafe.sbt:sbt-pgp:0.8.3 (sbtVersion=0.12, scalaVersion=2.9.2)

Any suggestions as how to solve said problem ?

**Comment by rahulpratapm** [comment]
Have you tried running `./sbt update`?

**Comment by gustavo-momente** [comment]
Just tried, and I got the same error, here's the full log: 



    using java from the search path
    [info] Loading project definition from /home/uusuario/Downloads/twofishes-0.90.0/project
    [warn] Multiple resolvers having different access mechanism configured with same name 'sbt-plugin-releases'. To avoid conflict, Remove duplicate project resolvers (`resolvers`) or rename publishing resolver (`publishTo`).
    [info] Updating {file:/home/uusuario/Downloads/twofishes-0.90.0/project/}default-b6e9cc...
    [info] Resolving com.eed3si9n#sbt-assembly;0.9.2 ...
    [warn] 	module not found: com.eed3si9n#sbt-assembly;0.9.2
    [warn] ==== typesafe-ivy-releases: tried
    [warn]   http://repo.typesafe.com/typesafe/ivy-releases/com.eed3si9n/sbt-assembly/scala_2.9.2/sbt_0.12/0.9.2/ivys/ivy.xml
    [warn] ==== sbt-plugin-releases: tried
    [warn]   http://scalasbt.artifactoryonline.com/scalasbt/sbt-plugin-releases/com.eed3si9n/sbt-assembly/scala_2.9.2/sbt_0.12/0.9.2/ivys/ivy.xml
    [warn] ==== local: tried
    [warn]   /home/uusuario/.ivy2/local/com.eed3si9n/sbt-assembly/scala_2.9.2/sbt_0.12/0.9.2/ivys/ivy.xml
    [warn] ==== sbt-plugin-releases: tried
    [warn]   http://scalasbt.artifactoryonline.com/scalasbt/sbt-plugin-releases/com.eed3si9n/sbt-assembly/scala_2.9.2/sbt_0.12/0.9.2/ivys/ivy.xml
    [warn] ==== public: tried
    [warn]   http://repo1.maven.org/maven2/com/eed3si9n/sbt-assembly_2.9.2_0.12/0.9.2/sbt-assembly-0.9.2.pom
    [info] Resolving com.foursquare#spindle-codegen-plugin;3.0.0-M4 ...
    [info] Resolving net.virtual-void#sbt-dependency-graph;0.7.4 ...
    [info] Resolving com.github.mdr#ascii-graphs_2.9.2;0.0.2 ...
    [info] Resolving org.scala-lang#scala-library;2.9.2 ...
    [info] Resolving com.typesafe.sbt#sbt-pgp;0.8.3 ...
    [warn] 	module not found: com.typesafe.sbt#sbt-pgp;0.8.3
    [warn] ==== typesafe-ivy-releases: tried
    [warn]   http://repo.typesafe.com/typesafe/ivy-releases/com.typesafe.sbt/sbt-pgp/scala_2.9.2/sbt_0.12/0.8.3/ivys/ivy.xml
    [warn] ==== sbt-plugin-releases: tried
    [warn]   http://scalasbt.artifactoryonline.com/scalasbt/sbt-plugin-releases/com.typesafe.sbt/sbt-pgp/scala_2.9.2/sbt_0.12/0.8.3/ivys/ivy.xml
    [warn] ==== local: tried
    [warn]   /home/uusuario/.ivy2/local/com.typesafe.sbt/sbt-pgp/scala_2.9.2/sbt_0.12/0.8.3/ivys/ivy.xml
    [warn] ==== sbt-plugin-releases: tried
    [warn]   http://scalasbt.artifactoryonline.com/scalasbt/sbt-plugin-releases/com.typesafe.sbt/sbt-pgp/scala_2.9.2/sbt_0.12/0.8.3/ivys/ivy.xml
    [warn] ==== public: tried
    [warn]   http://repo1.maven.org/maven2/com/typesafe/sbt/sbt-pgp_2.9.2_0.12/0.8.3/sbt-pgp-0.8.3.pom
    [info] Resolving org.scala-sbt#sbt;0.12.1 ...
    [info] Resolving org.scala-sbt#main;0.12.1 ...
    [info] Resolving org.scala-sbt#actions;0.12.1 ...
    [info] Resolving org.scala-sbt#classpath;0.12.1 ...
    [info] Resolving org.scala-sbt#launcher-interface;0.12.1 ...
    [info] Resolving org.scala-sbt#interface;0.12.1 ...
    [info] Resolving org.scala-sbt#io;0.12.1 ...
    [info] Resolving org.scala-sbt#control;0.12.1 ...
    [info] Resolving org.scala-lang#scala-compiler;2.9.2 ...
    [info] Resolving org.scala-sbt#completion;0.12.1 ...
    [info] Resolving org.scala-sbt#collections;0.12.1 ...
    [info] Resolving jline#jline;1.0 ...
    [info] Resolving org.scala-sbt#api;0.12.1 ...
    [info] Resolving org.scala-sbt#compiler-integration;0.12.1 ...
    [info] Resolving org.scala-sbt#incremental-compiler;0.12.1 ...
    [info] Resolving org.scala-sbt#logging;0.12.1 ...
    [info] Resolving org.scala-sbt#process;0.12.1 ...
    [info] Resolving org.scala-sbt#compile;0.12.1 ...
    [info] Resolving org.scala-sbt#persist;0.12.1 ...
    [info] Resolving org.scala-tools.sbinary#sbinary_2.9.0;0.4.0 ...
    [info] Resolving org.scala-sbt#classfile;0.12.1 ...
    [info] Resolving org.scala-sbt#compiler-ivy-integration;0.12.1 ...
    [info] Resolving org.scala-sbt#ivy;0.12.1 ...
    [info] Resolving org.apache.ivy#ivy;2.3.0-rc1 ...
    [info] Resolving com.jcraft#jsch;0.1.46 ...
    [info] Resolving commons-httpclient#commons-httpclient;3.1 ...
    [info] Resolving commons-logging#commons-logging;1.0.4 ...
    [info] Resolving commons-codec#commons-codec;1.2 ...
    [info] Resolving org.scala-sbt#run;0.12.1 ...
    [info] Resolving org.scala-sbt#task-system;0.12.1 ...
    [info] Resolving org.scala-sbt#tasks;0.12.1 ...
    [info] Resolving org.scala-sbt#tracking;0.12.1 ...
    [info] Resolving org.scala-sbt#cache;0.12.1 ...
    [info] Resolving org.scala-sbt#testing;0.12.1 ...
    [info] Resolving org.scala-sbt#test-agent;0.12.1 ...
    [info] Resolving org.scala-tools.testing#test-interface;0.5 ...
    [info] Resolving org.scala-sbt#command;0.12.1 ...
    [info] Resolving org.scala-sbt#compiler-interface;0.12.1 ...
    [info] Resolving org.scala-sbt#precompiled-2_8_2;0.12.1 ...
    [info] Resolving org.scala-sbt#precompiled-2_10_0-m7;0.12.1 ...
    [warn] 	::::::::::::::::::::::::::::::::::::::::::::::
    [warn] 	::          UNRESOLVED DEPENDENCIES         ::
    [warn] 	::::::::::::::::::::::::::::::::::::::::::::::
    [warn] 	:: com.eed3si9n#sbt-assembly;0.9.2: not found
    [warn] 	:: com.typesafe.sbt#sbt-pgp;0.8.3: not found
    [warn] 	::::::::::::::::::::::::::::::::::::::::::::::
    [warn] 
    [warn] 	Note: Some unresolved dependencies have extra attributes.  Check that these dependencies exist with the requested attributes.
    [warn] 		com.eed3si9n:sbt-assembly:0.9.2 (sbtVersion=0.12, scalaVersion=2.9.2)
    [warn] 		com.typesafe.sbt:sbt-pgp:0.8.3 (sbtVersion=0.12, scalaVersion=2.9.2)
    [warn] 
    sbt.ResolveException: unresolved dependency: com.eed3si9n#sbt-assembly;0.9.2: not found
    unresolved dependency: com.typesafe.sbt#sbt-pgp;0.8.3: not found
    	at sbt.IvyActions$.sbt$IvyActions$$resolve(IvyActions.scala:214)
    	at sbt.IvyActions$$anonfun$update$1.apply(IvyActions.scala:122)
    	at sbt.IvyActions$$anonfun$update$1.apply(IvyActions.scala:121)
    	at sbt.IvySbt$Module$$anonfun$withModule$1.apply(Ivy.scala:114)
    	at sbt.IvySbt$Module$$anonfun$withModule$1.apply(Ivy.scala:114)
    	at sbt.IvySbt$$anonfun$withIvy$1.apply(Ivy.scala:102)
    	at sbt.IvySbt.liftedTree1$1(Ivy.scala:49)
    	at sbt.IvySbt.action$1(Ivy.scala:49)
    	at sbt.IvySbt$$anon$3.call(Ivy.scala:58)
    	at xsbt.boot.Locks$GlobalLock.withChannel$1(Locks.scala:98)
    	at xsbt.boot.Locks$GlobalLock.withChannelRetries$1(Locks.scala:81)
    	at xsbt.boot.Locks$GlobalLock$$anonfun$withFileLock$1.apply(Locks.scala:102)
    	at xsbt.boot.Using$.withResource(Using.scala:11)
    	at xsbt.boot.Using$.apply(Using.scala:10)
    	at xsbt.boot.Locks$GlobalLock.ignoringDeadlockAvoided(Locks.scala:62)
    	at xsbt.boot.Locks$GlobalLock.liftedTree1$1(Locks.scala:52)
    	at xsbt.boot.Locks$GlobalLock.withLock(Locks.scala:52)
    	at xsbt.boot.Locks$.apply0(Locks.scala:31)
    	at xsbt.boot.Locks$.apply(Locks.scala:28)
    	at sbt.IvySbt.withDefaultLogger(Ivy.scala:58)
    	at sbt.IvySbt.withIvy(Ivy.scala:99)
    	at sbt.IvySbt.withIvy(Ivy.scala:95)
    	at sbt.IvySbt$Module.withModule(Ivy.scala:114)
    	at sbt.IvyActions$.update(IvyActions.scala:121)
    	at sbt.Classpaths$$anonfun$work$1$1.apply(Defaults.scala:951)
    	at sbt.Classpaths$$anonfun$work$1$1.apply(Defaults.scala:949)
    	at sbt.Classpaths$$anonfun$doWork$1$1$$anonfun$54.apply(Defaults.scala:972)
    	at sbt.Classpaths$$anonfun$doWork$1$1$$anonfun$54.apply(Defaults.scala:970)
    	at sbt.Tracked$$anonfun$lastOutput$1.apply(Tracked.scala:35)
    	at sbt.Classpaths$$anonfun$doWork$1$1.apply(Defaults.scala:974)
    	at sbt.Classpaths$$anonfun$doWork$1$1.apply(Defaults.scala:969)
    	at sbt.Tracked$$anonfun$inputChanged$1.apply(Tracked.scala:45)
    	at sbt.Classpaths$.cachedUpdate(Defaults.scala:977)
    	at sbt.Classpaths$$anonfun$45.apply(Defaults.scala:856)
    	at sbt.Classpaths$$anonfun$45.apply(Defaults.scala:853)
    	at sbt.Scoped$$anonfun$hf10$1.apply(Structure.scala:586)
    	at sbt.Scoped$$anonfun$hf10$1.apply(Structure.scala:586)
    	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:49)
    	at sbt.Scoped$Reduced$$anonfun$combine$1$$anonfun$apply$12.apply(Structure.scala:311)
    	at sbt.Scoped$Reduced$$anonfun$combine$1$$anonfun$apply$12.apply(Structure.scala:311)
    	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:41)
    	at sbt.std.Transform$$anon$5.work(System.scala:71)
    	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:232)
    	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:232)
    	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:18)
    	at sbt.Execute.work(Execute.scala:238)
    	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:232)
    	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:232)
    	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
    	at sbt.CompletionService$$anon$2.call(CompletionService.scala:30)
    	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
    	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
    	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    	at java.lang.Thread.run(Thread.java:745)
    [error] (*:update) sbt.ResolveException: unresolved dependency: com.eed3si9n#sbt-assembly;0.9.2: not found
    [error] unresolved dependency: com.typesafe.sbt#sbt-pgp;0.8.3: not found
    Project loading failed: (r)etry, (q)uit, (l)ast, or (i)gnore? q


Moreover, I'm using release 0.90.0 from the release page, but it seems that the [travis build](https://travis-ci.org/foursquare/twofishes/builds/73115270) is facing the same problem for the master branch.

**Comment by rahulpratapm** [comment]
Seems like this has to do with scalasbt.artifactoryonline.com being down:

http://forums.jfrog.org/Scalasbt-artifactory-down-td7580393.html

Will see if I can pull these dependencies from somewhere else.

**Comment by notadoctor** [comment]
Adding an additional resolver for the new bintray repo to `project/plugins.sbt` fixed this issue for me.

`resolvers += Resolver.url("bintray-sbt-plugins", url("http://dl.bintray.com/sbt/sbt-plugin-releases"))(Resolver.ivyStylePatterns)`

Don't know if there's a better / cleaner way to be doing that.

**Comment by rahulpratapm** [comment]
Excellent. Thanks! Going to push shortly.

**Comment by rahulpratapm** [comment]
Hmm. Now the Travis CI build fails with a different error:

https://travis-ci.org/foursquare/twofishes/builds/74505306

I'm not going to be able to investigate right away. Any ideas?

**Comment by notadoctor** [comment]
My resulting `project/plugins.sbt` file is here: https://gist.github.com/notadoctor/4b60867db288a8cc8e8c

The errors there look like they're coming from bad params being sent to sbt. Was the test working before the plugins file change?
